macro(outter_macro a)
  macro(inner_macro a)
    tkl_test_assert_true("\"${a}\" STREQUAL \"111\"" "1 a=${a}")
    if ("${a}" STREQUAL "111")
      tkl_test_assert_true(1)
    else()
      tkl_test_assert_true(0 "2 a=${a}")
    endif()
  endmacro()
endmacro()

outter_macro(111)
inner_macro(222)

function(outter_func a)
  macro(inner_macro a)
    tkl_test_assert_true("\"${a}\" STREQUAL \"222\"" "1 a=${a}")
    if ("${a}" STREQUAL "222")
      tkl_test_assert_true(1)
    else()
      tkl_test_assert_true(0 "2 a=${a}")
    endif()
  endmacro()
endfunction()

outter_func(111)
inner_macro(222)
