set(a 222)
set(prefix "\\")
set(suffix "\${a}")

macro(inner_macro v)
  #message("inner_macro v=${v}")
  tkl_test_assert_true("\"${v}\" STREQUAL \"${prefix}111${suffix}\"" "1 ${v} == ${prefix}111${suffix}")
  if ("${v}" STREQUAL "${prefix}111${suffix}")
    tkl_test_assert_true(1 "2 v=${v}")
  else()
    tkl_test_assert_true(0 "3 v=${v}")
  endif()
endmacro()

macro(outter_macro v)
  #message("outter_macro v=${v}")
  inner_macro("${v}")
endmacro()

function(outter_function v)
  #message("outter_function v=${v}")
  inner_macro("${v}")
endfunction()

outter_macro("\\\\\\\\111\\\\\\\${a}")
outter_function("\\\\111\\\${a}")
