@echo off

if /i "%TACKLELIB_SCRIPTS_INIT0_DIR%" == "%~dp0" exit /b

call "%%~dp0__init__.bat" || exit /b

set "TACKLELIB_SCRIPTS_INIT0_DIR=%~dp0"

if not defined NEST_LVL set NEST_LVL=0

for %%i in (PROJECT_ROOT ^
  PROJECT_CACHE_ROOT PROJECT_LOG_ROOT PROJECT_CONFIG_ROOT PROJECT_SCRIPTS_ROOT PROJECT_SCRIPTS_TOOLS_ROOT TACKLELIB_PROJECT_EXTERNALS_ROOT PROJECT_CMAKE_ROOT ^
  PROJECT_OUTPUT_ROOT PROJECT_OUTPUT_CONFIG_ROOT PROJECT_OUTPUT_CMAKE_ROOT ^
  CONTOOLS_ROOT ^
  TACKLELIB_BASH_SCRIPTS_ROOT TACKLELIB_PYTHON_SCRIPTS_ROOT ^
  CMDOPLIB_PYTHON_SCRIPTS_ROOT ^
  CONFIG_VARS_SYSTEM_FILE_IN CONFIG_VARS_SYSTEM_FILE CONFIG_VARS_USER_FILE_IN CONFIG_VARS_USER_FILE) do (
  if not defined %%i (
    echo.%~nx0: error: `%%i` variable is not defined.
    exit 255
  ) >&2
)

exit /b 0
