#pragma once

#define UTILITY_PP_STRINGIZE_(x) #x
#define UTILITY_PP_STRINGIZE(x) UTILITY_PP_STRINGIZE_(x)

#define UTILITY_PP_STRINGIZE_WIDE(x) UTILITY_PP_CONCAT(L, UTILITY_PP_STRINGIZE(x))

#define UTILITY_PP_CONCAT_(x, y) x ## y
#define UTILITY_PP_CONCAT(x, y) UTILITY_PP_CONCAT_(x, y)

#define UTILITY_PP_FILE_ __FILE__
#define UTILITY_PP_FILE UTILITY_PP_FILE_

#define UTILITY_PP_FILE_WIDE UTILITY_PP_CONCAT(L, UTILITY_PP_FILE)

#define UTILITY_PP_LINE_ __LINE__
#define UTILITY_PP_LINE UTILITY_PP_LINE_

#define UTILITY_PP_IDENTITY(x) x
#define UTILITY_PP_IDENTITY_(x) UTILITY_PP_IDENTITY_(x)
#define UTILITY_PP_IDENTITY2(v1, v2) UTILITY_PP_IDENTITY2_(v1, v2)
#define UTILITY_PP_IDENTITY2_(v1, v2) v1, v2

#define UTILITY_PP_LINE_TERMINATOR
